-- Phase 12: AI-Powered Predictive Analytics & Automation

-- ML model definitions and metadata
CREATE TABLE ml_models (
  id VARCHAR(255) PRIMARY KEY DEFAULT gen_random_uuid()::varchar,
  name VARCHAR(255) NOT NULL,
  model_type VARCHAR(100) NOT NULL, -- sales_forecast, labor_demand, inventory_optimization, anomaly_detection, equipment_failure
  algorithm VARCHAR(100), -- linear_regression, time_series, random_forest, neural_network
  version VARCHAR(50) NOT NULL,
  description TEXT,
  training_data_period_days INTEGER DEFAULT 90,
  features JSONB, -- List of input features used
  hyperparameters JSONB, -- Model configuration
  accuracy_metrics JSONB, -- MAE, RMSE, R2, etc.
  is_active BOOLEAN DEFAULT true,
  trained_at TIMESTAMP,
  trained_by VARCHAR(255) REFERENCES users(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ml_models_type ON ml_models(model_type);
CREATE INDEX idx_ml_models_active ON ml_models(is_active);

-- Predictions generated by ML models
CREATE TABLE predictions (
  id VARCHAR(255) PRIMARY KEY DEFAULT gen_random_uuid()::varchar,
  model_id VARCHAR(255) NOT NULL REFERENCES ml_models(id),
  prediction_type VARCHAR(100) NOT NULL, -- sales, labor_hours, inventory_order, failure_risk
  location_id VARCHAR(255) REFERENCES locations(id),
  prediction_date DATE NOT NULL,
  prediction_horizon VARCHAR(50), -- next_hour, next_day, next_week, next_month
  predicted_value NUMERIC NOT NULL,
  confidence_score NUMERIC, -- 0-100 confidence percentage
  lower_bound NUMERIC, -- Confidence interval lower
  upper_bound NUMERIC, -- Confidence interval upper
  input_features JSONB, -- Features used for this prediction
  actual_value NUMERIC, -- Filled in after the fact for accuracy tracking
  accuracy_percentage NUMERIC, -- Calculated after actual value known
  metadata JSONB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  evaluated_at TIMESTAMP -- When actual value was recorded
);

CREATE INDEX idx_predictions_model ON predictions(model_id);
CREATE INDEX idx_predictions_location ON predictions(location_id);
CREATE INDEX idx_predictions_date ON predictions(prediction_date);
CREATE INDEX idx_predictions_type ON predictions(prediction_type);

-- Automated recommendations based on predictions
CREATE TABLE smart_recommendations (
  id VARCHAR(255) PRIMARY KEY DEFAULT gen_random_uuid()::varchar,
  recommendation_type VARCHAR(100) NOT NULL, -- schedule_adjustment, inventory_order, price_change, staffing_alert
  location_id VARCHAR(255) REFERENCES locations(id),
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  rationale TEXT, -- Why this recommendation was made
  priority VARCHAR(20) DEFAULT 'medium', -- low, medium, high, urgent
  confidence_score NUMERIC, -- 0-100
  predicted_impact JSONB, -- Expected cost savings, revenue increase, etc.
  recommendation_data JSONB NOT NULL, -- Specific action details
  source_prediction_id VARCHAR(255) REFERENCES predictions(id),
  status VARCHAR(50) DEFAULT 'pending', -- pending, accepted, rejected, expired, auto_applied
  created_by_model_id VARCHAR(255) REFERENCES ml_models(id),
  reviewed_by VARCHAR(255) REFERENCES users(id),
  reviewed_at TIMESTAMP,
  applied_at TIMESTAMP,
  expires_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_recommendations_location ON smart_recommendations(location_id);
CREATE INDEX idx_recommendations_status ON smart_recommendations(status);
CREATE INDEX idx_recommendations_type ON smart_recommendations(recommendation_type);
CREATE INDEX idx_recommendations_priority ON smart_recommendations(priority);

-- Anomaly detection results
CREATE TABLE anomalies (
  id VARCHAR(255) PRIMARY KEY DEFAULT gen_random_uuid()::varchar,
  anomaly_type VARCHAR(100) NOT NULL, -- sales_spike, sales_drop, labor_variance, temp_pattern, task_delay, inventory_shrinkage
  location_id VARCHAR(255) REFERENCES locations(id),
  detected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  severity VARCHAR(20) DEFAULT 'medium', -- low, medium, high, critical
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  metric_name VARCHAR(100), -- Which metric showed anomaly
  expected_value NUMERIC,
  actual_value NUMERIC,
  deviation_percentage NUMERIC,
  confidence_score NUMERIC, -- How confident we are this is truly an anomaly
  related_entity_type VARCHAR(100), -- tasks, temperatures, sales, inventory
  related_entity_id VARCHAR(255),
  root_cause_hypothesis TEXT,
  requires_investigation BOOLEAN DEFAULT false,
  status VARCHAR(50) DEFAULT 'detected', -- detected, investigating, resolved, false_positive
  investigated_by VARCHAR(255) REFERENCES users(id),
  investigated_at TIMESTAMP,
  resolution_notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_anomalies_location ON anomalies(location_id);
CREATE INDEX idx_anomalies_type ON anomalies(anomaly_type);
CREATE INDEX idx_anomalies_severity ON anomalies(severity);
CREATE INDEX idx_anomalies_status ON anomalies(status);
CREATE INDEX idx_anomalies_detected ON anomalies(detected_at DESC);

-- Automated actions taken by the system
CREATE TABLE automated_actions (
  id VARCHAR(255) PRIMARY KEY DEFAULT gen_random_uuid()::varchar,
  action_type VARCHAR(100) NOT NULL, -- create_order, adjust_schedule, send_alert, update_price
  location_id VARCHAR(255) REFERENCES locations(id),
  trigger_type VARCHAR(100) NOT NULL, -- prediction, anomaly, threshold, scheduled
  trigger_id VARCHAR(255), -- ID of prediction, anomaly, or rule that triggered
  action_details JSONB NOT NULL,
  status VARCHAR(50) DEFAULT 'pending', -- pending, executing, completed, failed, cancelled
  execution_result JSONB,
  error_message TEXT,
  requires_approval BOOLEAN DEFAULT false,
  approved_by VARCHAR(255) REFERENCES users(id),
  approved_at TIMESTAMP,
  executed_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_automated_actions_location ON automated_actions(location_id);
CREATE INDEX idx_automated_actions_type ON automated_actions(action_type);
CREATE INDEX idx_automated_actions_status ON automated_actions(status);
CREATE INDEX idx_automated_actions_trigger ON automated_actions(trigger_type, trigger_id);

-- Automation rules (user-defined triggers)
CREATE TABLE automation_rules (
  id VARCHAR(255) PRIMARY KEY DEFAULT gen_random_uuid()::varchar,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  rule_type VARCHAR(100) NOT NULL, -- threshold_based, time_based, prediction_based, event_based
  location_id VARCHAR(255) REFERENCES locations(id),
  trigger_condition JSONB NOT NULL, -- Condition logic
  action_config JSONB NOT NULL, -- What to do when triggered
  is_active BOOLEAN DEFAULT true,
  requires_approval BOOLEAN DEFAULT true,
  last_triggered_at TIMESTAMP,
  trigger_count INTEGER DEFAULT 0,
  created_by VARCHAR(255) REFERENCES users(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_automation_rules_location ON automation_rules(location_id);
CREATE INDEX idx_automation_rules_type ON automation_rules(rule_type);
CREATE INDEX idx_automation_rules_active ON automation_rules(is_active);

-- Pattern recognition and insights
CREATE TABLE insights (
  id VARCHAR(255) PRIMARY KEY DEFAULT gen_random_uuid()::varchar,
  insight_type VARCHAR(100) NOT NULL, -- trend, correlation, seasonality, optimization_opportunity
  category VARCHAR(100), -- sales, labor, inventory, compliance, efficiency
  location_id VARCHAR(255) REFERENCES locations(id),
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  significance_score NUMERIC, -- 0-100, how important/actionable
  timeframe VARCHAR(100), -- daily, weekly, monthly, seasonal
  discovered_pattern JSONB, -- Statistical pattern details
  recommended_actions TEXT[],
  potential_value JSONB, -- Estimated savings/revenue opportunity
  supporting_data JSONB,
  is_actionable BOOLEAN DEFAULT false,
  status VARCHAR(50) DEFAULT 'active', -- active, acted_upon, dismissed, expired
  discovered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  acted_upon_at TIMESTAMP,
  dismissed_by VARCHAR(255) REFERENCES users(id)
);

CREATE INDEX idx_insights_location ON insights(location_id);
CREATE INDEX idx_insights_type ON insights(insight_type);
CREATE INDEX idx_insights_significance ON insights(significance_score DESC);
CREATE INDEX idx_insights_status ON insights(status);

-- Forecast accuracy tracking
CREATE TABLE forecast_accuracy (
  id VARCHAR(255) PRIMARY KEY DEFAULT gen_random_uuid()::varchar,
  model_id VARCHAR(255) NOT NULL REFERENCES ml_models(id),
  location_id VARCHAR(255) REFERENCES locations(id),
  forecast_period_start DATE NOT NULL,
  forecast_period_end DATE NOT NULL,
  prediction_type VARCHAR(100) NOT NULL,
  total_predictions INTEGER,
  accurate_predictions INTEGER, -- Within acceptable threshold
  mae NUMERIC, -- Mean Absolute Error
  rmse NUMERIC, -- Root Mean Squared Error
  mape NUMERIC, -- Mean Absolute Percentage Error
  r_squared NUMERIC, -- R² score
  calculated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_forecast_accuracy_model ON forecast_accuracy(model_id);
CREATE INDEX idx_forecast_accuracy_location ON forecast_accuracy(location_id);
CREATE INDEX idx_forecast_accuracy_period ON forecast_accuracy(forecast_period_start, forecast_period_end);

-- Views for analytics

-- Daily prediction accuracy view
CREATE VIEW prediction_accuracy_summary AS
SELECT
  p.model_id,
  m.name as model_name,
  p.prediction_type,
  p.location_id,
  l.name as location_name,
  COUNT(*) as total_predictions,
  COUNT(*) FILTER (WHERE p.actual_value IS NOT NULL) as evaluated_predictions,
  AVG(p.accuracy_percentage) as avg_accuracy,
  AVG(p.confidence_score) as avg_confidence,
  MAX(p.created_at) as latest_prediction_at
FROM predictions p
JOIN ml_models m ON p.model_id = m.id
LEFT JOIN locations l ON p.location_id = l.id
WHERE p.created_at >= CURRENT_DATE - INTERVAL '30 days'
GROUP BY p.model_id, m.name, p.prediction_type, p.location_id, l.name;

-- Active recommendations needing review
CREATE VIEW pending_recommendations AS
SELECT
  sr.*,
  l.name as location_name,
  m.name as model_name,
  EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - sr.created_at))/3600 as age_hours
FROM smart_recommendations sr
LEFT JOIN locations l ON sr.location_id = l.id
LEFT JOIN ml_models m ON sr.created_by_model_id = m.id
WHERE sr.status = 'pending'
  AND (sr.expires_at IS NULL OR sr.expires_at > CURRENT_TIMESTAMP)
ORDER BY sr.priority DESC, sr.created_at ASC;

-- Anomaly patterns for investigation
CREATE VIEW anomaly_patterns AS
SELECT
  a.anomaly_type,
  a.location_id,
  l.name as location_name,
  COUNT(*) as occurrence_count,
  AVG(a.deviation_percentage) as avg_deviation,
  MAX(a.detected_at) as last_occurrence,
  COUNT(*) FILTER (WHERE a.status = 'resolved') as resolved_count,
  COUNT(*) FILTER (WHERE a.status = 'false_positive') as false_positive_count
FROM anomalies a
LEFT JOIN locations l ON a.location_id = l.id
WHERE a.detected_at >= CURRENT_DATE - INTERVAL '90 days'
GROUP BY a.anomaly_type, a.location_id, l.name;

-- Pre-seed initial ML models (placeholders for actual trained models)
INSERT INTO ml_models (id, name, model_type, algorithm, version, description, features, is_active) VALUES
('model-sales-forecast', 'Sales Forecaster', 'sales_forecast', 'time_series', '1.0', 'Predicts daily sales based on historical patterns, day of week, seasonality', '["historical_sales", "day_of_week", "month", "weather", "events"]', true),
('model-labor-demand', 'Labor Demand Predictor', 'labor_demand', 'linear_regression', '1.0', 'Predicts required labor hours based on forecasted sales', '["predicted_sales", "day_of_week", "historical_labor", "efficiency_ratio"]', true),
('model-inventory-opt', 'Inventory Optimizer', 'inventory_optimization', 'time_series', '1.0', 'Predicts optimal inventory levels and reorder points', '["historical_usage", "lead_time", "seasonality", "waste_rate"]', true),
('model-equipment-failure', 'Equipment Failure Predictor', 'equipment_failure', 'random_forest', '1.0', 'Predicts likelihood of equipment failure based on temperature patterns', '["temp_variance", "age", "maintenance_history", "usage_intensity"]', true),
('model-anomaly-detector', 'Anomaly Detector', 'anomaly_detection', 'statistical', '1.0', 'Detects unusual patterns in operations using statistical methods', '["z_score", "moving_average", "standard_deviation"]', true);

-- Pre-seed common automation rules
INSERT INTO automation_rules (id, name, description, rule_type, trigger_condition, action_config, requires_approval) VALUES
('rule-auto-order-low-stock', 'Auto-Order Low Stock Items', 'Automatically create purchase orders when inventory falls below reorder point', 'threshold_based', '{"metric": "inventory_quantity", "operator": "less_than", "threshold_field": "reorder_point"}', '{"action": "create_purchase_order", "vendor_selection": "preferred"}', true),
('rule-alert-high-temp', 'Alert on High Temperature Variance', 'Send urgent alert when temperature readings show unusual patterns', 'prediction_based', '{"prediction_type": "equipment_failure", "confidence_threshold": 70}', '{"action": "send_notification", "priority": "urgent", "channels": ["sms", "push"]}', false),
('rule-schedule-optimization', 'Optimize Weekly Schedules', 'Suggest schedule adjustments based on predicted labor demand', 'time_based', '{"schedule": "weekly", "day": "thursday"}', '{"action": "create_recommendation", "type": "schedule_adjustment"}', true);

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO pattyshack_user;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO pattyshack_user;
