version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pattyshack-db
    environment:
      POSTGRES_DB: pattyshack
      POSTGRES_USER: pattyshack_user
      POSTGRES_PASSWORD: pattyshack_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pattyshack_user -d pattyshack"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
